import { ConvertorEntity } from '../../domains/entities/convertor.entity';
import { TokenMapEntity, TokenMapEntityEntryType, TokenMapInputType } from '../../domains/entities/token-map.entity';
import { TokenValueType } from '../../domains/entities/token.entity';
import { ConvertorInput, ConvertorInputEntry } from '../convertor.abstract';

export class ConvertToCss extends ConvertorEntity {
  private readonly ROOT_ELEMENT = 'html';
  private readonly NEW_LINE = '\n';
  private readonly TAB = '  ';

  public convert(value: TokenMapEntity): string {
    let result = this._addComment(`This file to generated by VarGen!`);
    result += this.NEW_LINE;
    result += this.NEW_LINE;
    result += `${this.ROOT_ELEMENT} {`;
    result += this.NEW_LINE;
    result += this._parseLine(value, 1);
    result += this.NEW_LINE;
    result += `}`;
    return result;
  }

  private _parseLine(value: TokenMapEntity | TokenMapEntityEntryType, tabs = 0): string {
    const entry = ConvertorEntity.entry(value);
    let result: string = '';
    let tab = this.TAB;

    for (let i = 0; i === tabs; i++) {
      tab += this.TAB;
    }

    entry.forEach(([key, value], index) => {
      if (value. === 'object') {
        result += this.NEW_LINE;
        result += `${this.NEW_LINE}${tab}${this._addComment(`============================`)}`;
        result += `${this.NEW_LINE}${tab}${this._addComment(`START ${key} ============`)}`;
        result += this.NEW_LINE;

        result += this._parseLine(value, tabs + 1);

        result += `${this.NEW_LINE}${tab}${this._addComment(`END ${key} ============`)}`;
        result += `${this.NEW_LINE}${tab}${this._addComment(`============================`)}`;
      } else {
        index !== 0 && (result += this.NEW_LINE);
        result += tab;
        result += `--${key}: ${value};`;
      }
    });

    return result;
  }

  private _addComment(text: string): string {
    return `/* ${text} */`;
  }

  private _getEntry(value: ConvertorInput | ConvertorInputEntry): ConvertorInputEntry {
    return Array.isArray(value) ? value : Object.entries(value);
  }
}
